### ISSUE TITLE
iOS 使用 iAppStore 在榜單中無菜單選項功能

### ISSUE THREAD

**Issue by jay900604** [37iOS/iAppStore-SwiftUI#12]
iOS 使用 iAppStore 在榜單中無菜單選項功能，無法切換地區和排行榜

**Comment by iHTCboy** [comment]
@jay900604 你好，不太理解你说的问题，可以补充一下截图或者描述一下你具体的执行场景啊~ 🤣

**Comment by 37MobileTech** [comment]
@jay900604 看到在 iOS 17 beta 上显示不出来

**Comment by jay900604** [comment]
是的，無法在iOS17正常使用，有可能可以修復嗎?

**Comment by iHTCboy** [comment]
@jay900604 好的，等下个月有时间修复啊

**Comment by iHTCboy** [comment]
@jay900604 已经修复，可以更新新版本看看~
