### ISSUE TITLE
Bug好多

### ISSUE THREAD

**Issue by Lightning-Lion** [37iOS/iAppStore-SwiftUI#2]
水平属实不太行😅
iPhone一横屏导航页就卡Bug。
好多地方明明有系统组件却不用（比如搜索页），而自己造的组件漏洞百出。
简单提几个改进点，希望不要重蹈覆辙↓
1.（首页）不标准的Menu
2.（搜索页）不标准的Searchable
3..（设置页）不标准的DisclosureGroup
以上所有东西都有系统组件，而开发者又造了一遍（就算是为了兼容旧版系统），但实现效果远逊于原生组件。
知道自己技术菜就老老实实用原生组件！再不济就第三方库。

**Comment by iHTCboy** [comment]
@Lightning-Lion 你好，感谢反馈。

**首先声明一下**，目前，本项目只是开发者按自己想要的效果实现，按自己的设计编写代码。所以，Bug 或者不优雅的地方在所难免。

1. Bug多
答：请问有那些bug？ 横屏导航页适配是 SwiftUI 本身的问题，目前没有优化适配。

2. 明明有系统组件却不用，而自己造的组件漏洞百出。
答： 你说的搜索页，有什么漏洞？有劳你具体指正一下啊。

3.简单提几个改进点
答：因为 iAppStore 是高仿 App Store 的设计和 UI，所以是本着尽量还原 UI 效果，而不是系统有什么我就一定用系统。

（首页）不标准的Menu。
答：因为 Menu 包装只能有 10 个子控件。另外，想要的效果不是 Menu 的展示效果。
![image](https://user-images.githubusercontent.com/11418363/150143107-1b8c6e08-6a15-4395-a85d-a4cd16184914.png)


（搜索页）不标准的 Searchable
答：如上，高仿 App Store UI。Searchable因为没有搜索预览词的 API，所以没有实现。

（设置页）不标准的DisclosureGroup
答：UI 并不想实现 Disclosure 的效果，所以没有使用。

4.开发者又造了一遍（就算是为了兼容旧版系统），但实现效果远逊于原生组件。
答：请问为什么一定要用原生组件，实现效果远逊于原生组件这个结论怎么推导出来？


5.知道自己技术菜就老老实实用原生组件！再不济就第三方库。
答： Readme 已经写出来，并不想用第三方库。做过移动开发的朋友都知道，没有人要求你一定用原生组件。另外，第三方库的目的是什么？

**最后，本项目是一个开源的项目，欢迎大家有创意，或者更高的 UI 设计水平，欢迎给我们提 PR。**

**Comment by Lightning-Lion** [comment]
# 1.还“SwiftUI 本身的问题”？是你自己不会用NavigationView。
NavigationLink会自动为destination页面继承导航条，不需要在Destination页中手动创建NavigationView（相反，这样的结果是导致嵌套的NavigationView）
### 修改前
两个相互嵌套的导航栏，详情页无法正常显示↓
![修改前](https://user-images.githubusercontent.com/85005672/150300229-665b40d0-954b-4e84-a566-4c4fd115b3ae.png)
### 修改后
![修改后](https://user-images.githubusercontent.com/85005672/150300581-4998e933-898f-4c05-8747-1b78b68cd64d.png)
完美的导航，支持侧拉↕︎
![image](https://user-images.githubusercontent.com/85005672/150300682-13572e71-3360-48ca-925c-a862ce7f3630.png)
@iHTCboy

**Comment by Lightning-Lion** [comment]
# 2.怎么连Group都忘了啊？ 还“Menu 包装只能有 10 个子控件”😅
![IMG_1339](https://user-images.githubusercontent.com/85005672/150302448-3774a12f-3e10-4efe-af8a-097c715b5071.png)
![IMG_1340](https://user-images.githubusercontent.com/85005672/150302477-d6e98255-6ec4-4962-80db-ca796c55b6c5.png)
@iHTCboy

**Comment by Lightning-Lion** [comment]
# 3.“UI 并不想实现 Disclosure 的效果，所以没有使用”？我看你是忘了有Disclosure这个东西！
**这是用Disclosure 的效果，是不是一模一样？**
### 修改前
![image](https://user-images.githubusercontent.com/85005672/150307796-9cccdd08-c093-4c69-b72f-942f820e946c.png)
### 修改后
![image](https://user-images.githubusercontent.com/85005672/150307702-7bbd3609-9de5-4090-b543-60fb9592e05f.png)
![IMB_sE1QNm](https://user-images.githubusercontent.com/85005672/150309241-79bbf24f-e2d7-4caf-9a12-e10274ce1f78.gif)

**Comment by Lightning-Lion** [comment]
# 综述：请使用SwiftUI原生组件。
你自己设计的组件，很多时候只抄到了皮毛，就比如Disclosure完美适配展开/收拢动画，不需要你再写
```swift
            if iconViewIsExpanded {
                Image(systemName: "chevron.down").imageScale(.small).foregroundColor(Color.tsmg_placeholderText)
            } else {
                Image(systemName: "chevron.right").imageScale(.small).foregroundColor(Color.tsmg_placeholderText)
            }
```
这样的动画了（并且原生动画向下箭头和向右箭头的切换是有旋转过渡的，而你仿制的就没考虑到这一点）；
### 要做一个负责的组件——如果你仿制不好，请直接使用系统组件。
系统组件提供完整的动画、交互体验；如果你确实要仿制，那请仔细观察系统组件、揣摩官方的人机交互指南，确保你能尽可能保留系统组件的细节——或者，用第三方库吧，（Github上Star多的）第三方库设计者是专业的交互工程师，在设计时的考虑比你严谨很多，比如很多第三方组件都会声明“完整的无障碍支持”。
>  ## 最后——请负责任地开发👍🏻
@iHTCboy

**Comment by Lightning-Lion** [comment]
# 再来点干货
> ### ⎡系统搜索框⎦是支持搜索预览词的，但你还是没发现

![image](https://user-images.githubusercontent.com/85005672/150313354-1d2062fb-4240-464c-8af7-a727b3fcb073.png)
实现代码：
```swift
                .searchable(text: .constant(""), prompt: "这是什么？？？")
```
## 哦，对了：还没修改App语言！
![image](https://user-images.githubusercontent.com/85005672/150315290-680e3591-39b7-4235-aae4-7ea16325ed0e.png)
修改后你会看到“Cancel”变成中文的“取消”了😎
![image](https://user-images.githubusercontent.com/85005672/150315423-8a0f92c9-63a6-482a-b89a-3bcff72f307b.png)
@iHTCboy

**Comment by iHTCboy** [comment]
> # 1.还“SwiftUI 本身的问题”？是你自己不会用NavigationView。
> NavigationLink会自动为destination页面继承导航条，不需要在Destination页中手动创建NavigationView（相反，这样的结果是导致嵌套的NavigationView）
> 

😀 好的，这个问题我的理解是SwiftUI的问题，感谢纠正，欢迎 PR 啊~  @Lightning-Lion

**Comment by iHTCboy** [comment]
> # 2.怎么连Group都忘了啊？ 还“Menu 包装只能有 10 个子控件”😅

@Lightning-Lion 嗯，这个知道的，我是说默认不能10个控件，但可以用 Group 或者 ForEach 解决。不用 Menu 就是不想用这样的效果。

**Comment by iHTCboy** [comment]
> # 3.“UI 并不想实现 Disclosure 的效果，所以没有使用”？我看你是忘了有Disclosure这个东西！
> **这是用Disclosure 的效果，是不是一模一样？**
> 

感谢反馈，这是一个好的优化建议，后续我们会改进啊，也欢迎 PR 。@Lightning-Lion

**Comment by iHTCboy** [comment]
> # 综述：请使用SwiftUI原生组件。
> 你自己设计的组件，很多时候只抄到了皮毛，就比如Disclosure完美适配展开/收拢动画，不需要你再写
> 

感谢你的建议，我们会认识聆听和改进。本身开源也是希望跟大家一起交流进步，项目在开发过程，并没有打磨完美就开源，另外，开源的目的是一起学习和进步，如果你一定要开源就有完善的交互和体验也不太现实，毕竟我们这不是商业的产品，所以，为了提高我们的交互体验，欢迎大家 PR ~ @Lightning-Lion

**Comment by iHTCboy** [comment]
> # 再来点干货
> > ### ⎡系统搜索框⎦是支持搜索预览词的，但你还是没发现

好的，谢谢反馈。项目中有尝试，源码有注释掉：

https://github.com/37iOS/iAppStore-SwiftUI/blob/main/iAppStore/components/search/SearchHome.swift

55行开始：
```
//        if #available(iOS 15.0, *) {
//            .searchable(text: $searchText, placement: .toolbar, prompt: "游戏、App 等", suggestions: {
//                Text("🍎").searchCompletion("apple")
//                Text("🍐").searchCompletion("pear")
//                Text("🍌").searchCompletion("banana")
//            }).onSubmit(of: .search) {
//                print(searchText)
//            }
//        }
```

但因接口需要 iOS15+，并且 SwiftUI 还没有提供兼容的方案，所以暂时不考虑使用。 请问你是否有可行的兼容方案吗？ @Lightning-Lion

**Comment by iHTCboy** [comment]
resolved v1.1.1 ：

1. 横屏导航页显示不全的问题；
2. 切换图标改用 DisclosureGroup。

再次感谢 @Lightning-Lion 反馈~
